package com.spongyt.wimo.repository;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER".
 */
public class Order {

    private Long id;
    /** Not-null value. */
    private String orderNumber;
    private String shipper;

    public Order() {
    }

    public Order(Long id) {
        this.id = id;
    }

    public Order(Long id, String orderNumber, String shipper) {
        this.id = id;
        this.orderNumber = orderNumber;
        this.shipper = shipper;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderNumber() {
        return orderNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getShipper() {
        return shipper;
    }

    public void setShipper(String shipper) {
        this.shipper = shipper;
    }

}
