package com.spongyt.wimo.repository;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER".
 */
public class Order {

    private Long id;
    /** Not-null value. */
    private String orderNumber;
    private String name;
    private String shipper;
    private String deliveryState;
    private String deliveryStateText;
    private Boolean isSentByUser;
    private Boolean isSynced;
    private Long createdTimeStamp;

    public Order() {
    }

    public Order(Long id) {
        this.id = id;
    }

    public Order(Long id, String orderNumber, String name, String shipper, String deliveryState, String deliveryStateText, Boolean isSentByUser, Boolean isSynced, Long createdTimeStamp) {
        this.id = id;
        this.orderNumber = orderNumber;
        this.name = name;
        this.shipper = shipper;
        this.deliveryState = deliveryState;
        this.deliveryStateText = deliveryStateText;
        this.isSentByUser = isSentByUser;
        this.isSynced = isSynced;
        this.createdTimeStamp = createdTimeStamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderNumber() {
        return orderNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShipper() {
        return shipper;
    }

    public void setShipper(String shipper) {
        this.shipper = shipper;
    }

    public String getDeliveryState() {
        return deliveryState;
    }

    public void setDeliveryState(String deliveryState) {
        this.deliveryState = deliveryState;
    }

    public String getDeliveryStateText() {
        return deliveryStateText;
    }

    public void setDeliveryStateText(String deliveryStateText) {
        this.deliveryStateText = deliveryStateText;
    }

    public Boolean getIsSentByUser() {
        return isSentByUser;
    }

    public void setIsSentByUser(Boolean isSentByUser) {
        this.isSentByUser = isSentByUser;
    }

    public Boolean getIsSynced() {
        return isSynced;
    }

    public void setIsSynced(Boolean isSynced) {
        this.isSynced = isSynced;
    }

    public Long getCreatedTimeStamp() {
        return createdTimeStamp;
    }

    public void setCreatedTimeStamp(Long createdTimeStamp) {
        this.createdTimeStamp = createdTimeStamp;
    }

}
